-- Fixer Comment (DON'T DELETE)
INSERT INTO Buttons
VALUES
    ('AAA0', 'Game Over', 'red'),
    ('AAB0', 'Continue', 'grey'),
    ('AAC0', '"Yes."', 'white'),
    ('AAD0', '"No."', 'white'),
    ('AAE0', 'CENSORED', 'red'),
    ('AAF0', 'Don''t.', 'white'),
    ('???0', 'ERROR: ROUTE INCOMPLETE! PICK SOMETHING ELSE OR DIE!', 'green'),
    ('AAG0', '"Why?"', 'white'),
    ('AAA1', '"Oi, watch it!"', 'white'),
    ('AAB1', '"Hey, I''ll sue you for that!"', 'white'),
    ('AAC1', '"Sounds good."', 'white'),
    ('AAD1', 'Get out of bed and make breakfast.', 'white'),
    ('AAE1', '"Actually, let''s just stay at home."', 'white'),
    ('AAF1', '"Peter! Make me my breakfast!"', 'white'),
    ('AAG1', 'Stare at the ice cream on the floor longingly.', 'white'),
    ('AAH1', '"Thanks."', 'white'),
    ('AAI1', '"Yeah. Don''t ask..."', 'white'),
    ('AAJ1', 'Turn around and start shooting.', 'white'),
    ('AAK1', 'Run.', 'white'),
    ('AAL1', '"Oh..."', 'white'),
    ('AAM1', '"I''m not a dick."', 'white'),
    ('AAN1', '"Screw you then."', 'white'),
    ('AAO1', '"My name is V{p1_name}."', 'white'),
    ('AAP1', '"Call me V{p1_name}."', 'white'),
    ('AAQ1', '"Fine, it''s V{p1_name}."', 'white'),
    ('AAR1', '"Sorry, it''s V{p1_name}."', 'white'),
    ('AAS1', '"Yeah, I''m not telling you."', 'white'),
    ('AAT1', '"A bomb?!"', 'white'),
    ('AAU1', '"..."', 'white'),
    ('AAV1', 'Stay put for now.', 'white'),
    ('AAW1', 'Attempt to kill them.', 'white'),
    ('AAX1', '"Do You want to see a magic trick?"', 'white'),
    ('AAY1', 'Struggle to attack them even more.', 'white'),
    ('AAZ1', '"You''ll see if you get me out of these binds..."', 'red'),
    ('ABA1', '"Wait what-"', 'white'),
    ('ABB1', '"What?"', 'white'),
    ('ABC1', '"What?!"', 'white'),
    ('ABD1', '"What?!?"', 'white'),
    ('ABE1', '"Thank goodness..."', 'white'),
    ('ABF1', '"Awww..."', 'white'),
    ('ABG1', '"Why don''t we go to the beach?"', 'white'),
    ('ABH1', '"Let''s just stay here."', 'white'),
    ('ABI1', '"How about you choose."', 'white'),
    ('ABJ1', '"Let''s each steal a plane and crash them into the Marina Towers!"', 'white'),
    ('ABK1', 'Stay there.', 'white'),
    ('ABL1', 'Escape.', 'white'),
    ('ABM1', '"You''re letting me go?"', 'white'),
    ('ABN1', '"Wait, no!"', 'white'),
    ('ABO1', '"No. I still haven''t forgotten about you killing Peter!"', 'white'),
    ('ABP1', '"Okay, thank you."', 'white'),
    ('ABQ1', '"Oh, what?"', 'white'),
    ('ABR1', 'Surrender.', 'white'),
    ('ABS1', 'Crawl away like a normal person.', 'white'),
    ('ABT1', '"Yeah?"', 'white'),
    ('ABU1', '"What do you mean?"', 'white'),
    ('ABV1', '"Wait what? I don''t know what you''re talking about!"', 'white'),
    ('ABW1', 'Do so.', 'white'),
    ('ABX1', 'G{Do so.}', 'red'),
    ('ABY1', 'Capitalism.', 'white'),
    ('ABZ1', 'Ikea.', 'white'),
    ('ACA1', 'Alcatraz.', 'white'),
    ('ACB1', 'Reload.', 'white'),
    ('ACC1', '"Yeah, but I wanted to escape. If you help me, I''ll reward you."', 'white'),
    ('ACD1', '"Uhhh..."', 'white'),
    ('ACE1', '"Is this enough?"', 'white'),
    ('ACF1', '"Cool."', 'white'),
    ('ACG1', '"Oh, shit."', 'white'),
    ('ACH1', '"Seriously?!"', 'white'),
    ('ACI1', '"Oh..."', 'white'),
    ('ACJ1', 'Do a "Die Hard".', 'white'),
    ('ACK1', '"You''ll never find me!"', 'white'),
    ('ACL1', 'Dig to the bomb room.', 'white'),
    ('ACM1', 'Drink bleach and the suspicious white washing powder.', 'white'),
    ('ACN1', '"Aw, shucks..."', 'white'),
    ('ACO1', 'Continue digging', 'grey'),
    ('ACP1', '"Hehe... shut uppp."', 'white'),
    ('ACQ1', '"Nah, I''m fiiiiine..."', 'white'),
    ('ACR1', '"Shushshhy you silly voice in my heaad..."', 'white'),
    ('ACS1', '"Good, ya shut your mouth! Or... whatever silly voices in my head have."', 'white'),
    ('ACT1', '"Haha, why are there so many people watching me?"', 'white'),
    ('ACU1', '"W-wait, I''m sowwy, scary voice! Don''t hurt me-', 'white'),
    ('ACV1', '"What about you? That means you''re fake."', 'white'),
    ('ACW1', 'Open the death menu screen and rip off The Matrix.', 'white'),
    ('ACX1', '"What is this?"', 'white'),
    ('ACY1', '"What now?"', 'white'),
    ('ACZ1', 'Take the green pill.', 'white'),
    ('ADA1', 'Take the yellow pill.', 'white'),
    ('ADB1', '"What''s the difference between the two? And shouldn''t they be red and blue?"', 'white'),
    ('ADC1', '"Hang-on, what-?', 'white'),
    ('ADD1', '"I feel weird..."', 'white'),
    ('ADE1', 'Play around with your powers.', 'white'),
    ('ADF1', 'Force lift everyone.', 'white'),
    ('ADG1', 'Fling the gun away.', 'white'),
    ('ADH1', '"Die, anarchists!"', 'white'),
    ('ADI1', '"H-huh...?"', 'white'),
    ('ADJ1', '"Well..."', 'white'),
    ('ADK1', '"Shoot..."', 'white'),
    ('ADL1', '"Wait what-?"', 'white'),
    ('ADM1', '"Fine."', 'white'),
    ('ADN1', '"Rude..."', 'white'),
    ('ADO1', '"Hey, let go of-"', 'white');

-- Extra Notes:
-- Button Template --> ('ADC1', '', 'white'),